-- MyTrees spatial layers stored as JSONB (created on first API sync as well).

CREATE TABLE IF NOT EXISTS mytrees_aftercare (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_apiary_assessment (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_beekeeping (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_carbon_measurements (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_carbon_plots (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_clusters (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_fires (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_infrastructure (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_infrastructure_verification (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_land_preparation (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_meetings (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_nurseries (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_nurseries_verification (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_planting (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_plot_selection (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_plots_assessment (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_plots_mapping (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_red_boundary (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_seed_bank (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_seed_collection (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_species_distribution (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_survival_count (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_user_tracks (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_verification (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_wards (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS mytrees_work_plan (id VARCHAR(255) PRIMARY KEY, fid VARCHAR(255), geometry JSONB, properties JSONB, synced_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
